global:
  nfConfigurationConfigMap: oai-5g-basic
  clusterIpServiceIpAllocation: true #this will allocate ip-address to cluster Ip service
  waitForNRF: true
  http2Param: "--http2-prior-knowledge"  # if waitForNRF is true and http2 is used for all NF then this param is needed
  timeout: 1
mysql:
  enabled: true
  imagePullPolicy: IfNotPresent
  oai5gdatabase: basic
  imagePullSecrets:
    - name: "regcred"
  persistence:
    enabled: false
oai-nrf:
  enabled: true
  kubernetesType: Vanilla #Openshift/Vanilla Vanilla for Upstream Kubernetes
  nfimage:  # image name either locally present or in a public/private repository
    repository: docker.io/oaisoftwarealliance/oai-nrf          ## The image will be pulled from dockerhub
    version: v2.0.0                          ## The branch to be used to pull from dockerhub
    # pullPolicy: IfNotPresent or Never or Always
    pullPolicy: IfNotPresent
  includeTcpDumpContainer: @TCPDUMP_CONTAINER@ #only for taking pcaps inside network function pod
  imagePullSecrets:
    - name: "regcred"
  config:
    logLevel: "debug"   #allowed info/error/debug
  nodeSelector: {}
oai-udr:
  enabled: true
  kubernetesType: Vanilla #Openshift/Vanilla Vanilla for Upstream Kubernetes
  nfimage:  # image name either locally present or in a public/private repository
    repository: docker.io/oaisoftwarealliance/oai-udr           ## The image will be pulled from dockerhub
    version: v2.0.0                                    ## The branch to be used to pull from dockerhub
    # pullPolicy: IfNotPresent or Never or Always
    pullPolicy: IfNotPresent
  includeTcpDumpContainer: @TCPDUMP_CONTAINER@ #only for taking pcaps inside network function pod
  imagePullSecrets:
    - name: "regcred"
  config:
    logLevel: "debug"   #allowed info/error/debug
  nodeSelector: {}
oai-udm:
  enabled: true
  kubernetesType: Vanilla #Openshift/Vanilla Vanilla for Upstream Kubernetes
  nfimage:  # image name either locally present or in a public/private repository
    repository: docker.io/oaisoftwarealliance/oai-udm           ## The image will be pulled from dockerhub
    version: v2.0.0                                    ## The branch to be used to pull from dockerhub
    # pullPolicy: IfNotPresent or Never or Always
    pullPolicy: IfNotPresent
  includeTcpDumpContainer: @TCPDUMP_CONTAINER@ #only for taking pcaps inside network function pod
  imagePullSecrets:
    - name: "regcred"
  config:
    logLevel: "debug"   #allowed info/error/debug
  nodeSelector: {}
oai-ausf:
  enabled: true
  kubernetesType: Vanilla #Openshift/Vanilla Vanilla for Upstream Kubernetes
  nfimage:  # image name either locally present or in a public/private repository
    repository: docker.io/oaisoftwarealliance/oai-ausf           ## The image will be pulled from dockerhub
    version: v2.0.0                                    ## The branch to be used to pull from dockerhub
    # pullPolicy: IfNotPresent or Never or Always
    pullPolicy: IfNotPresent
  start:
    tcpdump: @START_TCPDUMP@
  includeTcpDumpContainer: @TCPDUMP_CONTAINER@ #only for taking pcaps inside network function pod
  imagePullSecrets:
    - name: "regcred"
  securityContext:
    privileged: @PRIVILEGED@
  persistent:
    sharedvolume: @SHAREDVOLUME@
  config:
    logLevel: "debug"   #allowed info/error/debug
  nodeSelector: {}
oai-amf:
  enabled: true
  kubernetesType: Vanilla #Openshift/Vanilla Vanilla for Upstream Kubernetes
  nfimage:  # image name either locally present or in a public/private repository
    repository: docker.io/oaisoftwarealliance/oai-amf           ## The image will be pulled from dockerhub
    version: v2.0.0                                    ## The branch to be used to pull from dockerhub
    # pullPolicy: IfNotPresent or Never or Always
    pullPolicy: IfNotPresent
  start:
    tcpdump: @START_TCPDUMP@  
  includeTcpDumpContainer: @TCPDUMP_CONTAINER@ #only for taking pcaps inside network function pod
  imagePullSecrets:
    - name: "regcred"
  securityContext:
    privileged: @PRIVILEGED@
  persistent:
    sharedvolume: @SHAREDVOLUME@
  multus:
    ## If you don't want to add a default route in your pod then replace this field with ""
    defaultGateway: "@CN_DEFAULT_GW@"
    n2Interface:
      create: @MULTUS_AMF_N2@
      Ipadd: "@IP_AMF_N2@"
      Netmask: "@NETMASK_AMF_N2@"
      ## If you do not need a specific mac address leave the field empty
      Mac: "@MAC_AMF_N2@"
      # #name inside the pod is hardcoded right now
      # name: "n2"
      ## If you do not have a gateway leave the field empty
      Gateway: "@GW_AMF_N2@"
      ## If you do not want to add any routes in your pod then leave this field empty
      routes: "@ROUTES_AMF_N2@"
      hostInterface: "@IF_NAME_AMF_N2@" # Interface of the host machine on which this pod will be scheduled
  nodeSelector: {}
  nodeName: @NODE_AMF@
oai-upf:
  enabled: true
  kubernetesType: Vanilla #Openshift/Vanilla Vanilla for Upstream Kubernetes
  nfimage:  # image name either locally present or in a public/private repository
    repository: docker.io/oaisoftwarealliance/oai-upf    ## The image will be pulled from dockerhub
    version: v2.0.0                                    ## The branch to be used to pull from dockerhub
    # pullPolicy: IfNotPresent or Never or Always
    pullPolicy: IfNotPresent
  start:
    tcpdump: @START_TCPDUMP@  
  includeTcpDumpContainer: @TCPDUMP_CONTAINER@ #only for taking pcaps inside network function pod
  imagePullSecrets:
    - name: "regcred"
  securityContext:
    privileged: @PRIVILEGED@
  persistent:
    sharedvolume: @SHAREDVOLUME@
  # create an extra interface for N3 incase the gNB is outside the cluster network or there is a need to have dedicated interface for N3
  ## Change these ip-addresses according to your environment
  ## N4, N6 are optional only if you want that UPF uses different subnets for different 3gpp interfaces. 
  multus:
    ## If you don't want to add a default route in your pod then replace this field with ""
    defaultGateway: "@CN_DEFAULT_GW@"
    n3Interface:
      create: @MULTUS_UPF_N3@
      Ipadd: "@IP_UPF_N3@"
      Netmask: "@NETMASK_UPF_N3@"
      ## If you do not need a specific mac address leave the field empty
      Mac: "@MAC_UPF_N3@"
      # #name inside the pod is hardcoded right now
      # name: "n3"
      ## If you do not have a gateway leave the field empty
      Gateway: "@GW_UPF_N3@"
      ## If you don't want to add a default route in your pod then replace this field with ""
      routes: "@ROUTES_UPF_N3@"
      hostInterface: "@IF_NAME_UPF_N3@"
    ## For n4 it is better to re-use eth0 interface inside the pod (primary CNI of Kubernetes)
    n4Interface:
      create: @MULTUS_UPF_N4@
      Ipadd: "@IP_UPF_N4@
      Netmask: "@NETMASK_UPF_N4@"
      ## If you do not need a specific mac address leave the field empty
      Mac: "@MAC_UPF_N4@"
      # #name inside the pod is hardcoded right now
      # name: "n4"
      ## If you do not have a gateway leave the field empty
      Gateway: "@GW_UPF_N4@"
      ## If you do not want to add any routes in your pod then leave this field empty
      routes: "@ROUTES_UPF_N4@"
      hostInterface: "@IF_NAME_UPF_N4@"
    n6Interface:
      create: @MULTUS_UPF_N6@
      Ipadd: "@IP_UPF_N6@"
      # #name inside the pod is hardcoded right now
      # name: "n6"
      Netmask: "@NETMASK_UPF_N6@"
      ## If you do not need a specific mac address leave the field empty
      Mac: "@MAC_UPF_N6@"
      ## If you do not have a gateway leave the field empty
      Gateway: "@GW_UPF_N6@"
      ## If you do not want to add any routes in your pod then leave this field empty
      routes: "@ROUTES_UPF_N6@"
      hostInterface: "@IF_NAME_UPF_N6@"
  #NOTE: If the interface you selected for n6If is wrong then traffic will not be routed towards internet
  nodeSelector: {}
  nodeName: @NODE_UPF@ ###TO CHANGE IN OAI5G_RRU : SPGWU -> UPF###
# oai-traffic-server:
#  enabled: false
#  weight: 6
#  kubernetesType: Vanilla
#  trafficServer:
#    repository: docker.io/oaisoftwarealliance/trf-gen-cn5g
#    version: latest
#    #pullPolicy: IfNotPresent or Never or Always
#    pullPolicy: IfNotPresent
#  #Without multus traffic server won't be able to forward packets to upf if can't use server then add an extra container in upf with iperf3 or install iperf3 package in tcpdump container
#  multus:
#    create: true
#    IPadd: "172.21.6.99"
#    Netmask: "22"
#    defaultGateway: "172.21.7.254"
#    hostInterface: "bond0"	# Interface of the host machine on which this pod will be scheduled
#  config:
#    ueroute: 12.1.1.0/24
#    upfIpadd: 172.21.6.95
#    noOfIperf3Server: 10
oai-smf:
  enabled: true
  kubernetesType: Vanilla #Openshift/Vanilla Vanilla for Upstream Kubernetes
  nfimage:  # image name either locally present or in a public/private repository
    repository: docker.io/oaisoftwarealliance/oai-smf           ## The image will be pulled from dockerhub
    version: v2.0.0                         ## The branch to be used to pull from dockerhub
    # pullPolicy: IfNotPresent or Never or Always
    pullPolicy: IfNotPresent
  start:
    tcpdump: @START_TCPDUMP@  
  includeTcpDumpContainer: @TCPDUMP_CONTAINER@ #only for taking pcaps inside network function pod
  multus:
    ## If you don't want to add a default route in your pod then replace this field with ""
    defaultGateway: "@CN_DEFAULT_GW@"
    n4Interface:
      create: @MULTUS_SMF_N4@
      Ipadd: "@IP_SMF_N4@"
      Netmask: "@NETMASK_SMF_N4@"
      ## If you do not need a specific mac address leave the field empty
      Mac: "@MAC_SMF_N4@"
      ## If you do not have a gateway leave the field empty
      Gateway: "@GW_SMF_N4@"
      ## If you do not want to add any routes in your pod then leave this field empty
      routes: "@ROUTES_SMF_N4@"
      hostInterface: "@IF_NAME_SMF_N4@"
  nodeSelector: {}
  imagePullSecrets:
    - name: "regcred"
  securityContext:
    privileged: @PRIVILEGED@
  persistent:
    sharedvolume: @SHAREDVOLUME@
  nodeSelector: {}
  nodeName: @NODE_SMF@
